### ISSUE TITLE
PHP 5 not PHP 5.3 needed for part 1 of instructions

### ISSUE THREAD

**Issue by mjp337** [kaltura/Kaltura-Library-Export-Excel#1]
Great tool, but the directions indicate to "Download the Kaltura PHP 5.3+ API Client Library and extract into the /kaltura-client directory". But the 5.3+package from Kaltura does not contain the scripts referenced in this code (there's no file "KalturaClient.php, referenced in line 8). The correct files are located in the Kaltura PHP kit.

**Comment by kaltura-hooks** [comment]
Hi @mjp337,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi @mjp337,

We have multiple PHP client libs and it can be quite confusing.. 
The client to use with this repo is:
http://cdnbakmi.kaltura.com/content/clientlibs/php5_02-10-2017.tar.gz

This client can work with PHP >= 5.3.n and < 7.2.n.
I imagine the client you tried to use is:
http://cdnbakmi.kaltura.com/content/clientlibs/php53_02-10-2017.tar.gz

Which supports the same PHP versions but also utilises the namespaces feature, which was indeed introduced in PHP 5.3.0 and is hence sometimes referred to as 'php53'. That client has a diff directory structure, with diff file names and won't work out of the box with this repo.

We also have the ZF client, thus called because it follows the Zend Framework [ZF] coding styles.

Hope that explains it.

**Comment by jessp01** [comment]
I also added a download link to the README. Hopefully, this will make things clearer:)
