### ISSUE TITLE
No entries returned in output file

### ISSUE THREAD

**Issue by sage-freeman** [kaltura/Kaltura-Library-Export-Excel#3]
Thanks for creating and sharing this script. I've been using this for several years to download metadata from Kaltura. The current script runs without errors but does not seem to be returning any entries in the output file.

**Comment by kaltura-hooks** [comment]
Hi @sage-freeman,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello @sage-freeman,
Did you set `STOP_DATE_FOR_EXPORT` correctly? see https://github.com/kaltura/Kaltura-Library-Export-Excel/blob/master/accountdump.php#L31

Cheers,

**Comment by sage-freeman** [comment]
Hello @jessp01 ,

I am using default value of null. I also tried -1 but the result is still 0 entries returned. I do have an older working version of this script. I noticed that 'null' was in single quotes in the old script but did not make any difference in my testing.

**Comment by sage-freeman** [comment]
Hi @jessp01, 

thanks for your help. I am eager to get this script working. The new ENTRY_FIELDS you added are great! Especially lastPlayedAt.

We are running Kaltura SaaS and I've download the PHP5.3+ client. 

I have only modified the following:

PARTNER_ID
PARTNER_NAME
ADMIN_SECRET

The script completes successfully but still returns 0 entries.

**Comment by freednog** [comment]
I get the same thing - no entries returned. However, if I run the captions branch, it at least completes and pulls the URL for the captions files. Sadly, the branch does not have the other new entry fields which would be super helpful.

**Comment by freednog** [comment]
Hmm. when I change const PARENT_CATEGORIES = from '00000' to  '' (blank), the script seems to work. I just compared the newer script to the working branch.
