### ISSUE TITLE
Quiz entries?

### ISSUE THREAD

**Issue by alexumn** [kaltura/Kaltura-Library-Export-Excel#4]
Is there a way to export information about Quiz entries using this tool? I've tried using KalturaMediaType::QUIZ, KalturaMediaType::quiz, and KalturaMediaType::KalturaQuiz, no luck yet.

Thank you!

**Comment by kaltura-hooks** [comment]
Hi @alexumn,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by alexumn** [comment]
BTW, I realized that when the ENTRY_FIELDS array includes 'capabilities', that column in the output has "quiz.quiz" for quiz entries. That's good, but it would be nice to filter on KalturaMediaType up front.

**Comment by jessp01** [comment]
Hi @alexumn,

Please see https://forum.kaltura.org/t/quizzes-and-api/7534/2

**Comment by alexumn** [comment]
Thank you.

We were hoping for a quick list of all quiz entries. Using the API's service: quiz, action: list will show the number of quizzes, but not many details about that. An alternative is to use service: media, action: list with KalturaMediaEntryFilter's advancedSearch set to KalturaQuizAdvancedFilter: isQuiz = TRUE_VALUE. That gets media details only for quiz entries.

Closing this now...
